/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_myropcb_tocc_HelloJNI */

#ifndef _Included_com_myropcb_tocc_HelloJNI
#define _Included_com_myropcb_tocc_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_myropcb_tocc_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_myropcb_tocc_HelloJNI_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_myropcb_tocc_HelloJNI
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_myropcb_tocc_HelloJNI_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
